<div class="container" id="form">
    <div class="form_content">
        <div class="title">
            <h1><?php echo $titulo;?></h1>
        </div>
 			<?php echo $this->form()->openTag($form)?>
			<?php echo $this->formElement($form->get('pessoa_cod'))?>
			
            <div class="form-group">
                <?php echo $this->formLabel($form->get('pessoa_nome'))?>
                <?php echo $this->formElement($form->get('pessoa_nome'))?>
                <?php echo $this->formElementErrors($form->get('pessoa_nome'))?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('pessoa_cpf'))?>
                <?php echo $this->formElement($form->get('pessoa_cpf'))?>
                <?php echo $this->formElementErrors($form->get('pessoa_cpf'))?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('pessoa_email'))?>
                <?php echo $this->formElement($form->get('pessoa_email'))?>
                <?php echo $this->formElementErrors($form->get('pessoa_email'))?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('pessoa_tel'))?>
                <?php echo $this->formElement($form->get('pessoa_tel'))?>
                <?php echo $this->formElementErrors($form->get('pessoa_tel'))?>
            </div>
            <?php echo $this->formElement($form->get('submit'))?>
        <?php echo $this->form()->closeTag($form)?>
    </div>
</div>



<table>
	<tbody style="margin-top=20px;">
		<tr>
			<td></td>
		</tr>
	</tbody>
	<!-- Botão -->

</table>

